/* global jest */

export default {
  badNesting: {
    input: [{"type":"LITERAL","name":"TEXT","chars":"foo ","index":0},{"name":"BOLD","type":"BLOCK_START","index":4,"pairedWith":13,"chars":"*","handle":"at","delimiters":{"open":"*","close":"*"}},{"type":"LITERAL","name":"TEXT","chars":"bar ","index":5},{"name":"UNDERLINE","type":"BLOCK_START","index":9,"pairedWith":18,"chars":"_","handle":"at","delimiters":{"open":"_","close":"_"}},{"type":"LITERAL","name":"TEXT","chars":"foo","index":10},{"name":"BOLD","index":13,"pairedWith":4,"type":"BLOCK_END","chars":"*","handle":"at","delimiters":{"open":"*","close":"*"}},{"type":"LITERAL","name":"TEXT","chars":" baz","index":14},{"name":"UNDERLINE","index":18,"pairedWith":9,"type":"BLOCK_END","chars":"_","handle":"at","delimiters":{"open":"_","close":"_"}}],
    expected: [{"type":"LITERAL","name":"TEXT","chars":"foo ","index":0},{"name":"BOLD","type":"BLOCK_START","index":4,"pairedWith":13,"chars":"*","handle":"at","delimiters":{"open":"*","close":"*"}},{"type":"LITERAL","name":"TEXT","chars":"bar ","index":5},{"name":"UNDERLINE","type":"BLOCK_START","index":9,"pairedWith":18,"chars":"_","handle":"at","delimiters":{"open":"_","close":"_"}},{"type":"LITERAL","name":"TEXT","chars":"foo","index":10},{"name":"UNDERLINE","type":"BLOCK_END","index":9,"pairedWith":18,"chars":"_","handle":"at","delimiters":{"open":"_","close":"_"},"start":null,"token":"_"},{"name":"BOLD","index":13,"pairedWith":4,"type":"BLOCK_END","chars":"*","handle":"at","delimiters":{"open":"*","close":"*"}},{"name":"UNDERLINE","type":"BLOCK_START","index":9,"pairedWith":18,"chars":"_","handle":"at","delimiters":{"open":"_","close":"_"},"start":null},{"type":"LITERAL","name":"TEXT","chars":" baz","index":14},{"name":"UNDERLINE","index":18,"pairedWith":9,"type":"BLOCK_END","chars":"_","handle":"at","delimiters":{"open":"_","close":"_"}}]
  },
  markUpSpansCells: {
    text: 'Step 1\tfoo2 *bar2 baz2\tlorem2 ipsum2*',
    input: [{"name":"TABLE_ROW","type":"RANGE_START","index":0,"chars":null,"handle":"before","priority":-0.02,"delimiters":{"open":null,"close":null}},{"name":"TABLE_CELL","type":"RANGE_START","index":0,"chars":null,"handle":"before","priority":-0.01,"delimiters":{"open":null,"close":null}},{"type":"LITERAL","name":"TEXT","chars":"Step 1","index":0},{"name":"TABLE_CELL","type":"RANGE_END","index":6,"chars":null,"handle":"before","priority":0.01,"delimiters":{"open":null,"close":null}},{"type":"LITERAL","name":"TEXT","chars":"\t","index":6},{"name":"TABLE_CELL","type":"RANGE_START","index":7,"chars":null,"handle":"before","priority":-0.01,"delimiters":{"open":null,"close":null}},{"type":"LITERAL","name":"TEXT","chars":"foo2 ","index":7},{"name":"BOLD","type":"BLOCK_START","index":12,"pairedWith":36,"chars":"*","handle":"at","delimiters":{"open":"*","close":"*"}},{"type":"LITERAL","name":"TEXT","chars":"bar2 baz2","index":13},{"name":"TABLE_CELL","type":"RANGE_END","index":22,"chars":null,"handle":"before","priority":0.01,"delimiters":{"open":null,"close":null}},{"type":"LITERAL","name":"TEXT","chars":"\t","index":22},{"name":"TABLE_CELL","type":"RANGE_START","index":23,"chars":null,"handle":"before","priority":-0.01,"delimiters":{"open":null,"close":null}},{"type":"LITERAL","name":"TEXT","chars":"lorem2 ipsum2","index":23},{"name":"BOLD","index":36,"pairedWith":12,"type":"BLOCK_END","chars":"*","handle":"at","delimiters":{"open":"*","close":"*"}},{"name":"TABLE_CELL","type":"RANGE_END","index":37,"chars":null,"handle":"before","priority":0.01,"delimiters":{"open":null,"close":null}},{"name":"TABLE_ROW","type":"RANGE_END","index":37,"chars":null,"handle":"before","priority":0.02,"delimiters":{"open":null,"close":null}}],
    expected:[{"name":"TABLE_ROW","type":"RANGE_START","index":0,"chars":null,"handle":"before","priority":-0.02,"delimiters":{"open":null,"close":null}},{"name":"TABLE_CELL","type":"RANGE_START","index":0,"chars":null,"handle":"before","priority":-0.01,"delimiters":{"open":null,"close":null}},{"type":"LITERAL","name":"TEXT","chars":"Step 1","index":0},{"name":"TABLE_CELL","type":"RANGE_END","index":6,"chars":null,"handle":"before","priority":0.01,"delimiters":{"open":null,"close":null}},{"type":"LITERAL","name":"TEXT","chars":"\t","index":6},{"name":"TABLE_CELL","type":"RANGE_START","index":7,"chars":null,"handle":"before","priority":-0.01,"delimiters":{"open":null,"close":null}},{"type":"LITERAL","name":"TEXT","chars":"foo2 ","index":7},{"name":"BOLD","type":"BLOCK_START","index":12,"pairedWith":36,"chars":"*","handle":"at","delimiters":{"open":"*","close":"*"}},{"type":"LITERAL","name":"TEXT","chars":"bar2 baz2","index":13},{"name":"TABLE_CELL","type":"RANGE_END","index":22,"chars":null,"handle":"before","priority":0.01,"delimiters":{"open":null,"close":null}},{"type":"LITERAL","name":"TEXT","chars":"\t","index":22},{"name":"TABLE_CELL","type":"RANGE_START","index":23,"chars":null,"handle":"before","priority":-0.01,"delimiters":{"open":null,"close":null}},{"type":"LITERAL","name":"TEXT","chars":"lorem2 ipsum2","index":23},{"name":"BOLD","index":36,"pairedWith":12,"type":"BLOCK_END","chars":"*","handle":"at","delimiters":{"open":"*","close":"*"}},{"name":"TABLE_CELL","type":"RANGE_END","index":37,"chars":null,"handle":"before","priority":0.01,"delimiters":{"open":null,"close":null}},{"name":"TABLE_ROW","type":"RANGE_END","index":37,"chars":null,"handle":"before","priority":0.02,"delimiters":{"open":null,"close":null}}],
  },
  tableInputs: {
    markUpInCell: 'Step 1\t*foo bar baz*\tlorem ipsum',
    markUpSpansCells: 'Step 1\tfoo2 *bar2 baz2\tlorem2 ipsum2*',
    overlappingMarkUpInCell: 'Step 1\t*foo2 _bar2* baz2_\tlorem2 ipsum2',
    overlappingMarkUpSpansCell:'Step 1\t*foo2 _bar2 baz2\tlorem2* ipsum2_',
  }
};
