/* global jest */

export default {
  badBlockNesting: {
    text: 'foo *bar _foo* baz_',
    input: [{"type":"LITERAL","name":"TEXT","chars":"foo ","index":0},{"name":"BOLD","type":"BLOCK_START","index":4,"pairedWith":13,"chars":"*","handle":"at","delimiters":{"open":"*","close":"*"}},{"type":"LITERAL","name":"TEXT","chars":"bar ","index":5},{"name":"UNDERLINE","type":"BLOCK_START","index":9,"pairedWith":18,"chars":"_","handle":"at","delimiters":{"open":"_","close":"_"}},{"type":"LITERAL","name":"TEXT","chars":"foo","index":10},{"name":"BOLD","index":13,"pairedWith":4,"type":"BLOCK_END","chars":"*","handle":"at","delimiters":{"open":"*","close":"*"}},{"type":"LITERAL","name":"TEXT","chars":" baz","index":14},{"name":"UNDERLINE","index":18,"pairedWith":9,"type":"BLOCK_END","chars":"_","handle":"at","delimiters":{"open":"_","close":"_"}}],
    expected: [{"type":"LITERAL","name":"TEXT","chars":"foo ","index":0},{"name":"BOLD","type":"BLOCK_START","index":4,"pairedWith":13,"chars":"*","handle":"at","delimiters":{"open":"*","close":"*"}},{"type":"LITERAL","name":"TEXT","chars":"bar ","index":5},{"name":"UNDERLINE","type":"BLOCK_START","index":9,"pairedWith":18,"chars":"_","handle":"at","delimiters":{"open":"_","close":"_"}},{"type":"LITERAL","name":"TEXT","chars":"foo","index":10},{"name":"UNDERLINE","type":"BLOCK_END","index":9,"pairedWith":18,"chars":"_","handle":"at","delimiters":{"open":"_","close":"_"},"_virtual":true},{"name":"BOLD","index":13,"pairedWith":4,"type":"BLOCK_END","chars":"*","handle":"at","delimiters":{"open":"*","close":"*"}},{"name":"UNDERLINE","type":"BLOCK_START","index":9,"pairedWith":18,"chars":"_","handle":"at","delimiters":{"open":"_","close":"_"},"_virtual":true},{"type":"LITERAL","name":"TEXT","chars":" baz","index":14},{"name":"UNDERLINE","index":18,"pairedWith":9,"type":"BLOCK_END","chars":"_","handle":"at","delimiters":{"open":"_","close":"_"}}]
  },
  overlappingRanges: {
    text: 'foo bar foo baz',
    input: [{"name":"FIND","type":"RANGE_START","chars":null,"index":0,"pairedWith":7,"delimiters":{"open":null,"close":null},"priority":7,"handle":"before"},{"type":"LITERAL","name":"TEXT","chars":"foo ","index":0},{"name":"MARK","type":"RANGE_START","chars":null,"index":4,"pairedWith":11,"delimiters":{"open":null,"close":null},"priority":15,"handle":"before"},{"type":"LITERAL","name":"TEXT","chars":"bar","index":4},{"name":"FIND","type":"RANGE_END","chars":null,"index":7,"pairedWith":0,"delimiters":{"open":null,"close":null},"priority":-7,"handle":"before"},{"type":"LITERAL","name":"TEXT","chars":" foo","index":7},{"name":"MARK","type":"RANGE_END","chars":null,"index":11,"pairedWith":4,"delimiters":{"open":null,"close":null},"priority":-15,"handle":"before"},{"type":"LITERAL","name":"TEXT","chars":" baz","index":11}],
    expected: [{"name":"FIND","type":"RANGE_START","chars":null,"index":0,"pairedWith":7,"delimiters":{"open":null,"close":null},"priority":7,"handle":"before"},{"type":"LITERAL","name":"TEXT","chars":"foo ","index":0},{"name":"MARK","type":"RANGE_START","chars":null,"index":4,"pairedWith":11,"delimiters":{"open":null,"close":null},"priority":15,"handle":"before"},{"type":"LITERAL","name":"TEXT","chars":"bar","index":4},{"name":"MARK","type":"RANGE_END","chars":null,"index":4,"pairedWith":11,"delimiters":{"open":null,"close":null},"priority":15,"handle":"before","_virtual":true},{"name":"FIND","type":"RANGE_END","chars":null,"index":7,"pairedWith":0,"delimiters":{"open":null,"close":null},"priority":-7,"handle":"before"},{"name":"MARK","type":"RANGE_START","chars":null,"index":4,"pairedWith":11,"delimiters":{"open":null,"close":null},"priority":15,"handle":"before","_virtual":true},{"type":"LITERAL","name":"TEXT","chars":" foo","index":7},{"name":"MARK","type":"RANGE_END","chars":null,"index":11,"pairedWith":4,"delimiters":{"open":null,"close":null},"priority":-15,"handle":"before"},{"type":"LITERAL","name":"TEXT","chars":" baz","index":11}]
  },
  blockSpansCells: {
    text: 'foo2 *bar2 baz2\tlorem2 ipsum2*',
    input: [{"name":"TABLE_ROW","type":"RANGE_START","index":0,"chars":null,"handle":"before","priority":-0.02,"delimiters":{"open":null,"close":null}},{"name":"TABLE_CELL","type":"RANGE_START","index":0,"chars":null,"handle":"before","priority":-0.01,"delimiters":{"open":null,"close":null}},{"type":"LITERAL","name":"TEXT","chars":"foo2 ","index":0},{"name":"BOLD","type":"BLOCK_START","index":5,"pairedWith":29,"chars":"*","handle":"at","delimiters":{"open":"*","close":"*"}},{"type":"LITERAL","name":"TEXT","chars":"bar2 baz2","index":6},{"name":"TABLE_CELL","type":"RANGE_END","index":15,"chars":null,"handle":"before","priority":0.01,"delimiters":{"open":null,"close":null}},{"type":"LITERAL","name":"TEXT","chars":"\t","index":15},{"name":"TABLE_CELL","type":"RANGE_START","index":16,"chars":null,"handle":"before","priority":-0.01,"delimiters":{"open":null,"close":null}},{"type":"LITERAL","name":"TEXT","chars":"lorem2 ipsum2","index":16},{"name":"BOLD","index":29,"pairedWith":5,"type":"BLOCK_END","chars":"*","handle":"at","delimiters":{"open":"*","close":"*"}},{"name":"TABLE_CELL","type":"RANGE_END","index":30,"chars":null,"handle":"before","priority":0.01,"delimiters":{"open":null,"close":null}},{"name":"TABLE_ROW","type":"RANGE_END","index":30,"chars":null,"handle":"before","priority":0.02,"delimiters":{"open":null,"close":null}}],
    expected: [{"name":"TABLE_ROW","type":"RANGE_START","index":0,"chars":null,"handle":"before","priority":-0.02,"delimiters":{"open":null,"close":null}},{"name":"TABLE_CELL","type":"RANGE_START","index":0,"chars":null,"handle":"before","priority":-0.01,"delimiters":{"open":null,"close":null}},{"type":"LITERAL","name":"TEXT","chars":"foo2 ","index":0},{"name":"BOLD","type":"BLOCK_START","index":5,"pairedWith":29,"chars":"*","handle":"at","delimiters":{"open":"*","close":"*"}},{"type":"LITERAL","name":"TEXT","chars":"bar2 baz2","index":6},{"name":"BOLD","type":"BLOCK_END","index":5,"pairedWith":29,"chars":"*","handle":"at","delimiters":{"open":"*","close":"*"},"_virtual":true},{"name":"TABLE_CELL","type":"RANGE_END","index":15,"chars":null,"handle":"before","priority":0.01,"delimiters":{"open":null,"close":null}},{"type":"LITERAL","name":"TEXT","chars":"\t","index":15},{"name":"TABLE_CELL","type":"RANGE_START","index":16,"chars":null,"handle":"before","priority":-0.01,"delimiters":{"open":null,"close":null}},{"type":"LITERAL","name":"TEXT","chars":"lorem2 ipsum2","index":16},{"name":"TABLE_CELL","type":"RANGE_END","index":30,"chars":null,"handle":"before","priority":0.01,"delimiters":{"open":null,"close":null}},{"name":"TABLE_ROW","type":"RANGE_END","index":30,"chars":null,"handle":"before","priority":0.02,"delimiters":{"open":null,"close":null}}]
  },
  rangeSpansCells: {
    text: 'foo2 *bar2 baz2\tlorem2 ipsum2*',
    input: [{"name":"TABLE_ROW","type":"RANGE_START","index":0,"chars":null,"handle":"before","priority":-0.02,"delimiters":{"open":null,"close":null}},{"name":"TABLE_CELL","type":"RANGE_START","index":0,"chars":null,"handle":"before","priority":-0.01,"delimiters":{"open":null,"close":null}},{"type":"LITERAL","name":"TEXT","chars":"foo2 ","index":0},{"name":"TEST","type":"RANGE_START","index":5,"pairedWith":29,"chars":"*","handle":"at","delimiters":{"open":"*","close":"*"}},{"type":"LITERAL","name":"TEXT","chars":"bar2 baz2","index":6},{"name":"TABLE_CELL","type":"RANGE_END","index":15,"chars":null,"handle":"before","priority":0.01,"delimiters":{"open":null,"close":null}},{"type":"LITERAL","name":"TEXT","chars":"\t","index":15},{"name":"TABLE_CELL","type":"RANGE_START","index":16,"chars":null,"handle":"before","priority":-0.01,"delimiters":{"open":null,"close":null}},{"type":"LITERAL","name":"TEXT","chars":"lorem2 ipsum2","index":16},{"name":"TEST","index":29,"pairedWith":5,"type":"RANGE_END","chars":"*","handle":"at","delimiters":{"open":"*","close":"*"}},{"name":"TABLE_CELL","type":"RANGE_END","index":30,"chars":null,"handle":"before","priority":0.01,"delimiters":{"open":null,"close":null}},{"name":"TABLE_ROW","type":"RANGE_END","index":30,"chars":null,"handle":"before","priority":0.02,"delimiters":{"open":null,"close":null}}],
    expected: [{"name":"TABLE_ROW","type":"RANGE_START","index":0,"chars":null,"handle":"before","priority":-0.02,"delimiters":{"open":null,"close":null}},{"name":"TABLE_CELL","type":"RANGE_START","index":0,"chars":null,"handle":"before","priority":-0.01,"delimiters":{"open":null,"close":null}},{"type":"LITERAL","name":"TEXT","chars":"foo2 ","index":0},{"name":"TEST","type":"RANGE_START","index":5,"pairedWith":29,"chars":"*","handle":"at","delimiters":{"open":"*","close":"*"}},{"type":"LITERAL","name":"TEXT","chars":"bar2 baz2","index":6},{"name":"TEST","type":"RANGE_END","index":5,"pairedWith":29,"chars":"*","handle":"at","delimiters":{"open":"*","close":"*"},"_virtual":true},{"name":"TABLE_CELL","type":"RANGE_END","index":15,"chars":null,"handle":"before","priority":0.01,"delimiters":{"open":null,"close":null}},{"type":"LITERAL","name":"TEXT","chars":"\t","index":15},{"name":"TABLE_CELL","type":"RANGE_START","index":16,"chars":null,"handle":"before","priority":-0.01,"delimiters":{"open":null,"close":null}},{"type":"LITERAL","name":"TEXT","chars":"lorem2 ipsum2","index":16},{"name":"TABLE_CELL","type":"RANGE_END","index":30,"chars":null,"handle":"before","priority":0.01,"delimiters":{"open":null,"close":null}},{"name":"TABLE_ROW","type":"RANGE_END","index":30,"chars":null,"handle":"before","priority":0.02,"delimiters":{"open":null,"close":null}}]
  },
  blockEndsInTable: {
    text: '*start\nfoo* bar baz\tlorem ipsum',
    input: [{"name":"BOLD","type":"BLOCK_START","index":0,"pairedWith":10,"chars":"*","handle":"at","delimiters":{"open":"*","close":"*"}},{"type":"LITERAL","name":"TEXT","chars":"start\n","index":1},{"name":"TABLE_ROW","type":"RANGE_START","index":7,"chars":null,"handle":"before","priority":-0.02,"delimiters":{"open":null,"close":null}},{"name":"TABLE_CELL","type":"RANGE_START","index":7,"chars":null,"handle":"before","priority":-0.01,"delimiters":{"open":null,"close":null}},{"type":"LITERAL","name":"TEXT","chars":"foo","index":7},{"name":"BOLD","index":10,"pairedWith":0,"type":"BLOCK_END","chars":"*","handle":"at","delimiters":{"open":"*","close":"*"}},{"type":"LITERAL","name":"TEXT","chars":" bar baz","index":11},{"name":"TABLE_CELL","type":"RANGE_END","index":19,"chars":null,"handle":"before","priority":0.01,"delimiters":{"open":null,"close":null}},{"type":"LITERAL","name":"TEXT","chars":"\t","index":19},{"name":"TABLE_CELL","type":"RANGE_START","index":20,"chars":null,"handle":"before","priority":-0.01,"delimiters":{"open":null,"close":null}},{"type":"LITERAL","name":"TEXT","chars":"lorem ipsum","index":20},{"name":"TABLE_CELL","type":"RANGE_END","index":31,"chars":null,"handle":"before","priority":0.01,"delimiters":{"open":null,"close":null}},{"name":"TABLE_ROW","type":"RANGE_END","index":31,"chars":null,"handle":"before","priority":0.02,"delimiters":{"open":null,"close":null}}],
    expected: [{"name":"BOLD","type":"BLOCK_START","index":0,"pairedWith":10,"chars":"*","handle":"at","delimiters":{"open":"*","close":"*"}},{"type":"LITERAL","name":"TEXT","chars":"start\n","index":1},{"name":"TABLE_ROW","type":"RANGE_START","index":7,"chars":null,"handle":"before","priority":-0.02,"delimiters":{"open":null,"close":null}},{"name":"TABLE_CELL","type":"RANGE_START","index":7,"chars":null,"handle":"before","priority":-0.01,"delimiters":{"open":null,"close":null}},{"type":"LITERAL","name":"TEXT","chars":"foo","index":7},{"type":"LITERAL","name":"TEXT","chars":" bar baz","index":11},{"name":"TABLE_CELL","type":"RANGE_END","index":19,"chars":null,"handle":"before","priority":0.01,"delimiters":{"open":null,"close":null}},{"type":"LITERAL","name":"TEXT","chars":"\t","index":19},{"name":"TABLE_CELL","type":"RANGE_START","index":20,"chars":null,"handle":"before","priority":-0.01,"delimiters":{"open":null,"close":null}},{"type":"LITERAL","name":"TEXT","chars":"lorem ipsum","index":20},{"name":"TABLE_CELL","type":"RANGE_END","index":31,"chars":null,"handle":"before","priority":0.01,"delimiters":{"open":null,"close":null}},{"name":"TABLE_ROW","type":"RANGE_END","index":31,"chars":null,"handle":"before","priority":0.02,"delimiters":{"open":null,"close":null}},{"name":"BOLD","type":"BLOCK_END","index":0,"pairedWith":10,"chars":"*","handle":"at","delimiters":{"open":"*","close":"*"},"_virtual":true}]
  },
  blockIsNotClosedinText: {
    text: 'This shouldnt happen based on how we make our regex to find matching pairs. it may happen in the event that an end token is pruned due to improper nesting in a table. see blockEndsInTable text for reference text. Tis is just a more readable set of test data',
    input: [{"name":"TEST","type":"RANGE_START","index":0,"pairedWith":10,"chars":"*","handle":"at","delimiters":{"open":"*","close":"*"}},{"type":"LITERAL","name":"TEXT","chars":"start\n","index":1}],
    expected: [{"name":"TEST","type":"RANGE_START","index":0,"pairedWith":10,"chars":"*","handle":"at","delimiters":{"open":"*","close":"*"}},{"type":"LITERAL","name":"TEXT","chars":"start\n","index":1},{"name":"TEST","type":"RANGE_END","index":0,"pairedWith":10,"chars":"*","handle":"at","delimiters":{"open":"*","close":"*"},"_virtual":true}]
  }
};
